-- VHDL Entity alien_game_lib.alien_cordinate.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 14:09:19 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_cordinate IS
   PORT( 
      clk    : IN     std_logic;
      enable : IN     std_logic;
      mux_en : IN     std_logic;
      rst    : IN     std_logic;
      x      : OUT    std_logic_vector (7 DOWNTO 0);
      y      : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END alien_cordinate ;

--
-- VHDL Architecture alien_game_lib.alien_cordinate.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 14:09:19 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF alien_cordinate IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(2 DOWNTO 0);
   SIGNAL q     : std_logic_vector(2 DOWNTO 0);
   SIGNAL y1    : std_logic_vector(2 DOWNTO 0);
   SIGNAL y2    : std_logic_vector(2 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT binary_one_hot
   PORT (
      binary_in   : IN     std_logic_vector (2 DOWNTO 0);
      one_hot_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT decerementer
   PORT (
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT incrementer
   PORT (
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : binary_one_hot USE ENTITY alien_game_lib.binary_one_hot;
   FOR ALL : decerementer USE ENTITY alien_game_lib.decerementer;
   FOR ALL : incrementer USE ENTITY alien_game_lib.incrementer;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   q <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_5reg_cval <= "100";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= dout1;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   y <= "00000001";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(q, dout, enable)
   BEGIN
      CASE enable IS
      WHEN '0' => dout1 <= q;
      WHEN '1' => dout1 <= dout;
      WHEN OTHERS => dout1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(y1, y2, mux_en)
   BEGIN
      CASE mux_en IS
      WHEN '0' => dout <= y1;
      WHEN '1' => dout <= y2;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_2 : binary_one_hot
      PORT MAP (
         binary_in   => q,
         one_hot_out => x
      );
   U_1 : decerementer
      PORT MAP (
         x => q,
         y => y2
      );
   U_0 : incrementer
      PORT MAP (
         x => q,
         y => y1
      );

END struct;
