-- VHDL Entity alien_game_lib.alien_direction.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 17:56:26 15.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY alien_direction IS
   PORT( 
      clk       : IN     std_logic;
      left      : IN     std_logic;
      right     : IN     std_logic;
      rst       : IN     std_logic;
      direction : OUT    std_logic
   );

-- Declarations

END alien_direction ;

--
-- VHDL Architecture alien_game_lib.alien_direction.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 17:56:26 15.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF alien_direction IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic;
   SIGNAL dout1 : std_logic;

   -- Implicit buffer signal declarations
   SIGNAL direction_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   direction_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout1;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(direction_internal, right, dout)
   BEGIN
      CASE dout IS
      WHEN '0' => dout1 <= direction_internal;
      WHEN '1' => dout1 <= right;
      WHEN OTHERS => dout1 <= 'X';
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_0' of 'or'
   dout <= right OR left;

   -- Instance port mappings.

   -- Implicit buffered output assignments
   direction <= direction_internal;

END struct;
