-- VHDL Entity alien_game_lib.c2_t0_hello_led.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-307-SPC)
--          at - 20:30:34  1.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t0_hello_led IS
   PORT( 
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t0_hello_led ;

--
-- VHDL Architecture alien_game_lib.c2_t0_hello_led.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-307-SPC)
--          at - 19:30:40  2.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t0_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   color_BGR <= x"0A00FF";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   x_coord <= "11101000";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   y_coord <= "00001010";

   -- Instance port mappings.

END struct;
