-- VHDL Entity alien_game_lib.c2_t2_hello_led.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-307-SPC)
--          at - 19:39:09  2.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t2_hello_led IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      sw0       : IN     std_logic;
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t2_hello_led ;

--
-- VHDL Architecture alien_game_lib.c2_t2_hello_led.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-307-SPC)
--          at - 19:39:09  2.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF c2_t2_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL x_coord1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coord1 : std_logic_vector(7 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL color_BGR_internal : std_logic_vector (23 DOWNTO 0);
   SIGNAL x_coord_internal   : std_logic_vector (7 DOWNTO 0);
   SIGNAL y_coord_internal   : std_logic_vector (7 DOWNTO 0);


   -- Component Declarations
   COMPONENT c2_t0_hello_led
   PORT (
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT c2_t1_hello_led
   PORT (
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c2_t0_hello_led USE ENTITY alien_game_lib.c2_t0_hello_led;
   FOR ALL : c2_t1_hello_led USE ENTITY alien_game_lib.c2_t1_hello_led;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(x_coord_internal, x_coord1, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => x_coord_internal <= x_coord_internal;
      WHEN '1' => x_coord_internal <= x_coord1;
      WHEN OTHERS => x_coord_internal <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(y_coord_internal, y_coord1, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => y_coord_internal <= y_coord_internal;
      WHEN '1' => y_coord_internal <= y_coord1;
      WHEN OTHERS => y_coord_internal <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(color_BGR_internal, sw0)
   BEGIN
      CASE sw0 IS
      WHEN '0' => color_BGR_internal <= color_BGR_internal;
      WHEN '1' => color_BGR_internal <= color_BGR_internal;
      WHEN OTHERS => color_BGR_internal <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_0 : c2_t0_hello_led
      PORT MAP (
         color_BGR => color_BGR_internal,
         x_coord   => x_coord_internal,
         y_coord   => y_coord_internal
      );
   U_5 : c2_t1_hello_led
      PORT MAP (
         btn       => btn,
         color_BGR => color_BGR_internal,
         x_coord   => x_coord1,
         y_coord   => y_coord1
      );

   -- Implicit buffered output assignments
   color_BGR <= color_BGR_internal;
   x_coord   <= x_coord_internal;
   y_coord   <= y_coord_internal;

END struct;
