-- VHDL Entity alien_game_lib.c2_t1_hello_led.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-307-SPC)
--          at - 20:37:58  1.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY c2_t1_hello_led IS
   PORT( 
      btn       : IN     std_logic_vector (3 DOWNTO 0);
      color_BGR : OUT    std_logic_vector (23 DOWNTO 0);
      x_coord   : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord   : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END c2_t1_hello_led ;

--
-- VHDL Architecture alien_game_lib.c2_t1_hello_led.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-307-SPC)
--          at - 19:38:05  2.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF c2_t1_hello_led IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout5 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout6 : std_logic_vector(7 DOWNTO 0);



BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'constval'
   dout <= x"FF0012";

   -- ModuleWare code(v1.12) for instance 'U_1' of 'constval'
   dout1 <= x"FF0045";

   -- ModuleWare code(v1.12) for instance 'U_2' of 'constval'
   dout4 <= "10100000";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout5 <= "10100000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout6 <= "01100100";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout3 <= "10100000";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(dout, dout1, btn)
   BEGIN
      CASE btn(1) IS
      WHEN '0' => color_BGR <= dout;
      WHEN '1' => color_BGR <= dout1;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(dout5, dout6, btn)
   BEGIN
      CASE btn(2) IS
      WHEN '0' => x_coord <= dout5;
      WHEN '1' => x_coord <= dout6;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(dout3, dout4, btn)
   BEGIN
      CASE btn(3) IS
      WHEN '0' => y_coord <= dout3;
      WHEN '1' => y_coord <= dout4;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- Instance port mappings.

END struct;
