-- VHDL Entity alien_game_lib.ce3_basic_alien.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 02:36:49 16.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY ce3_basic_alien IS
   PORT( 
      clk            : IN     std_logic;
      enable         : IN     std_logic;
      hit            : IN     std_logic;
      rst_n          : IN     std_logic;
      Alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      X_coordinate   : OUT    std_logic_vector (7 DOWNTO 0);
      Y_coordinate   : OUT    std_logic_vector (7 DOWNTO 0);
      alien_defeated : OUT    std_logic
   );

-- Declarations

END ce3_basic_alien ;

--
-- VHDL Architecture alien_game_lib.ce3_basic_alien.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 13:58:35 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF ce3_basic_alien IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL direction : std_logic;
   SIGNAL dout      : std_logic;
   SIGNAL dout1     : std_logic_vector(23 DOWNTO 0);
   SIGNAL dout2     : std_logic_vector(23 DOWNTO 0);

   -- Implicit buffer signal declarations
   SIGNAL X_coordinate_internal   : std_logic_vector (7 DOWNTO 0);
   SIGNAL alien_defeated_internal : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;

   -- Component Declarations
   COMPONENT alien_cordinate
   PORT (
      clk    : IN     std_logic ;
      enable : IN     std_logic ;
      mux_en : IN     std_logic ;
      rst    : IN     std_logic ;
      x      : OUT    std_logic_vector (7 DOWNTO 0);
      y      : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT alien_direction
   PORT (
      clk       : IN     std_logic ;
      left      : IN     std_logic ;
      right     : IN     std_logic ;
      rst       : IN     std_logic ;
      direction : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : alien_cordinate USE ENTITY alien_game_lib.alien_cordinate;
   FOR ALL : alien_direction USE ENTITY alien_game_lib.alien_direction;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   alien_defeated_internal <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   dout1 <= x"0A00FF";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout2 <= x"FF0045";

   -- ModuleWare code(v1.12) for instance 'U_3' of 'mux'
   u_3combo_proc: PROCESS(dout1, dout2, alien_defeated_internal)
   BEGIN
      CASE alien_defeated_internal IS
      WHEN '0' => Alien_color <= dout1;
      WHEN '1' => Alien_color <= dout2;
      WHEN OTHERS => Alien_color <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'or'
   dout <= alien_defeated_internal OR hit;

   -- Instance port mappings.
   U_0 : alien_cordinate
      PORT MAP (
         clk    => clk,
         enable => enable,
         mux_en => direction,
         rst    => rst_n,
         x      => X_coordinate_internal,
         y      => Y_coordinate
      );
   U_1 : alien_direction
      PORT MAP (
         clk       => clk,
         left      => X_coordinate_internal(0),
         right     => X_coordinate_internal(7),
         rst       => rst_n,
         direction => direction
      );

   -- Implicit buffered output assignments
   X_coordinate   <= X_coordinate_internal;
   alien_defeated <= alien_defeated_internal;

END struct;
