-- VHDL Entity alien_game_lib.decerementer.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 18:59:00 15.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY decerementer IS
   PORT( 
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END decerementer ;

--
-- VHDL Architecture alien_game_lib.decerementer.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 14:09:12 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF decerementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry  : std_logic;
   SIGNAL carry1 : std_logic;
   SIGNAL carry2 : std_logic;
   SIGNAL carry3 : std_logic;
   SIGNAL carry4 : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout0  : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout2  : std_logic;
   SIGNAL dout3  : std_logic;
   SIGNAL dout4  : std_logic;
   SIGNAL dout5  : std_logic;
   SIGNAL sum    : std_logic;
   SIGNAL sum1   : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_10' of 'split'
   SIGNAL mw_U_10temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout1 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_8' of 'constval'
   dout2 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout3 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_5' of 'or'
   dout <= carry OR carry1;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'or'

   -- ModuleWare code(v1.12) for instance 'U_10' of 'split'
   mw_U_10temp_din <= x;
   u_10combo_proc: PROCESS (mw_U_10temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_10temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout4 <= temp_din(1);
      dout5 <= temp_din(2);
   END PROCESS u_10combo_proc;

   -- Instance port mappings.
   U_0 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout1,
         sw1   => dout0,
         carry => carry4,
         sum   => y(0)
      );
   U_1 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout2,
         sw1   => dout4,
         carry => carry,
         sum   => sum1
      );
   U_2 : c1_t1_half_adder
      PORT MAP (
         sw0   => sum1,
         sw1   => carry4,
         carry => carry1,
         sum   => y(1)
      );
   U_3 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout3,
         sw1   => dout5,
         carry => carry2,
         sum   => sum
      );
   U_4 : c1_t1_half_adder
      PORT MAP (
         sw0   => sum,
         sw1   => dout,
         carry => carry3,
         sum   => y(2)
      );

END struct;
