-- VHDL Entity alien_game_lib.game_logic.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 06:28:38 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY game_logic IS
   PORT( 
      btn         : IN     std_logic_vector (3 DOWNTO 0);
      clk         : IN     std_logic;
      rst_n       : IN     std_logic;
      write_ready : IN     std_logic;
      color_BGR   : OUT    std_logic_vector (23 DOWNTO 0);
      frame_done  : OUT    std_logic;
      write       : OUT    std_logic;
      x_coord     : OUT    std_logic_vector (7 DOWNTO 0);
      y_coord     : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END game_logic ;

--
-- VHDL Architecture alien_game_lib.game_logic.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 06:28:38 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF game_logic IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL Alien_color    : std_logic_vector(23 DOWNTO 0);
   SIGNAL X_coordinate1  : std_logic_vector(7 DOWNTO 0);
   SIGNAL Y_coordinate   : std_logic_vector(7 DOWNTO 0);
   SIGNAL alien_defeated : std_logic;
   SIGNAL dout           : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout0          : std_logic;
   SIGNAL dout1          : std_logic;
   SIGNAL enable         : std_logic;
   SIGNAL gun_color      : std_logic_vector(23 DOWNTO 0);
   SIGNAL gun_px_idx     : std_logic_vector(2 DOWNTO 0);
   SIGNAL hit            : std_logic;
   SIGNAL module_select  : std_logic_vector(1 DOWNTO 0);
   SIGNAL x_coordinate   : std_logic_vector(7 DOWNTO 0);
   SIGNAL y_coordinate1  : std_logic_vector(7 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_7' of 'split'
   SIGNAL mw_U_7temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT ce3_basic_alien
   PORT (
      clk            : IN     std_logic ;
      enable         : IN     std_logic ;
      hit            : IN     std_logic ;
      rst_n          : IN     std_logic ;
      Alien_color    : OUT    std_logic_vector (23 DOWNTO 0);
      X_coordinate   : OUT    std_logic_vector (7 DOWNTO 0);
      Y_coordinate   : OUT    std_logic_vector (7 DOWNTO 0);
      alien_defeated : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT gun_module
   PORT (
      btn          : IN     std_logic_vector (3 DOWNTO 0);
      clk          : IN     std_logic ;
      enable       : IN     std_logic ;
      gun_px_idx   : IN     std_logic_vector (1 DOWNTO 0);
      rst_n        : IN     std_logic ;
      gun_color    : OUT    std_logic_vector (23 DOWNTO 0);
      x_coordinate : OUT    std_logic_vector (7 DOWNTO 0);
      y_coordinate : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT hit_detector
   PORT (
      alien_x_cord : IN     std_logic_vector (7 DOWNTO 0);
      clk          : IN     std_logic ;
      d            : IN     std_logic ;
      gun_x_cord   : IN     std_logic_vector (7 DOWNTO 0);
      rst_n        : IN     std_logic ;
      hit          : OUT    std_logic 
   );
   END COMPONENT;
   COMPONENT write_sequencer
   PORT (
      alien_defeated : IN     std_logic ;
      clk            : IN     std_logic ;
      rst            : IN     std_logic ;
      write_ready    : IN     std_logic ;
      enable         : OUT    std_logic ;
      frame_done     : OUT    std_logic ;
      gun_px_idx     : OUT    std_logic_vector (2 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : ce3_basic_alien USE ENTITY alien_game_lib.ce3_basic_alien;
   FOR ALL : gun_module USE ENTITY alien_game_lib.gun_module;
   FOR ALL : hit_detector USE ENTITY alien_game_lib.hit_detector;
   FOR ALL : write_sequencer USE ENTITY alien_game_lib.write_sequencer;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_9' of 'merge'
   dout <= dout1 & dout0;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'mux'
   u_4combo_proc: PROCESS(Y_coordinate, y_coordinate1, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => y_coord <= Y_coordinate;
      WHEN "01" => y_coord <= y_coordinate1;
      WHEN OTHERS => y_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_4combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'mux'
   u_5combo_proc: PROCESS(X_coordinate1, x_coordinate, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => x_coord <= X_coordinate1;
      WHEN "01" => x_coord <= x_coordinate;
      WHEN OTHERS => x_coord <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_5combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(Alien_color, gun_color, module_select)
   BEGIN
      CASE module_select IS
      WHEN "00" => color_BGR <= Alien_color;
      WHEN "01" => color_BGR <= gun_color;
      WHEN OTHERS => color_BGR <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'split'
   mw_U_7temp_din <= gun_px_idx;
   u_7combo_proc: PROCESS (mw_U_7temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_7temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout1 <= temp_din(1);
   END PROCESS u_7combo_proc;

   -- Instance port mappings.
   U_3 : ce3_basic_alien
      PORT MAP (
         clk            => clk,
         enable         => enable,
         hit            => hit,
         rst_n          => rst_n,
         Alien_color    => Alien_color,
         X_coordinate   => X_coordinate1,
         Y_coordinate   => Y_coordinate,
         alien_defeated => alien_defeated
      );
   U_2 : gun_module
      PORT MAP (
         btn          => btn,
         clk          => clk,
         enable       => enable,
         gun_px_idx   => dout,
         rst_n        => rst_n,
         gun_color    => gun_color,
         x_coordinate => x_coordinate,
         y_coordinate => y_coordinate1
      );
   U_1 : hit_detector
      PORT MAP (
         alien_x_cord => X_coordinate1,
         clk          => clk,
         d            => btn(1),
         gun_x_cord   => x_coordinate,
         rst_n        => rst_n,
         hit          => hit
      );
   U_0 : write_sequencer
      PORT MAP (
         alien_defeated => alien_defeated,
         clk            => clk,
         rst            => rst_n,
         write_ready    => write_ready,
         enable         => enable,
         frame_done     => frame_done,
         gun_px_idx     => gun_px_idx,
         module_select  => module_select,
         write          => write
      );

END struct;
