-- VHDL Entity alien_game_lib.gun_module.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 01:15:40 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY gun_module IS
   PORT( 
      btn          : IN     std_logic_vector (3 DOWNTO 0);
      clk          : IN     std_logic;
      enable       : IN     std_logic;
      gun_px_idx   : IN     std_logic_vector (1 DOWNTO 0);
      rst_n        : IN     std_logic;
      gun_color    : OUT    std_logic_vector (23 DOWNTO 0);
      x_coordinate : OUT    std_logic_vector (7 DOWNTO 0);
      y_coordinate : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END gun_module ;

--
-- VHDL Architecture alien_game_lib.gun_module.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 01:15:51 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF gun_module IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic;
   SIGNAL x1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL y1    : std_logic_vector(7 DOWNTO 0);


   -- Component Declarations
   COMPONENT gun_position_direction
   PORT (
      btn_value : IN     std_logic_vector (3 DOWNTO 0);
      clk       : IN     std_logic ;
      enable    : IN     std_logic ;
      rst       : IN     std_logic ;
      x1        : OUT    std_logic_vector (7 DOWNTO 0);
      y1        : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : gun_position_direction USE ENTITY alien_game_lib.gun_position_direction;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'constval'
   gun_color <= x"0A00FF";

   -- ModuleWare code(v1.12) for instance 'U_6' of 'constval'
   dout2 <= "01000000";

   -- ModuleWare code(v1.12) for instance 'U_7' of 'constval'
   dout3 <= '1';

   -- ModuleWare code(v1.12) for instance 'U_3' of 'lshift'
   u_3combo_proc : PROCESS (x1, dout3)
   VARIABLE temp_shift : std_logic_vector (0 DOWNTO 0);
   VARIABLE temp_dout : std_logic_vector (7 DOWNTO 0);
   VARIABLE temp_din : std_logic_vector (7 DOWNTO 0);
   BEGIN
      temp_shift(0) := dout3;
      temp_din := x1;
      FOR i IN 0 TO 0 LOOP
         IF (temp_shift(i) = '1') THEN
            temp_dout := (OTHERS => '0');
            temp_dout(7 DOWNTO 2**i) := temp_din(7 - 2**i DOWNTO 0);
         ELSIF (temp_shift(i) = '0') THEN
            temp_dout := temp_din;
         ELSE
            temp_dout := (OTHERS => 'X');
         END IF;
         temp_din := temp_dout;
      END LOOP;
      dout <= temp_dout;
   END PROCESS u_3combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'mux'
   u_1combo_proc: PROCESS(x1, dout, dout1, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => x_coordinate <= x1;
      WHEN "01" => x_coordinate <= x1;
      WHEN "10" => x_coordinate <= dout;
      WHEN "11" => x_coordinate <= dout1;
      WHEN OTHERS => x_coordinate <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_1combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'mux'
   u_2combo_proc: PROCESS(dout2, y1, gun_px_idx)
   BEGIN
      CASE gun_px_idx IS
      WHEN "00" => y_coordinate <= dout2;
      WHEN "01" => y_coordinate <= y1;
      WHEN "10" => y_coordinate <= y1;
      WHEN "11" => y_coordinate <= y1;
      WHEN OTHERS => y_coordinate <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_2combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'rshift'
   u_4combo_proc : PROCESS (x1, dout3)
   VARIABLE temp_shift : std_logic_vector (0 DOWNTO 0);
   VARIABLE temp_dout : std_logic_vector (7 DOWNTO 0);
   VARIABLE temp_din : std_logic_vector (7 DOWNTO 0);
   BEGIN
      temp_shift(0) := dout3;
      temp_din := x1;
      FOR i IN 0 TO 0 LOOP
         IF (temp_shift(i) = '1') THEN
            temp_dout := (OTHERS => '0');
            temp_dout(7 - 2**i DOWNTO 0) := temp_din(7 DOWNTO 2**i);
         ELSIF (temp_shift(i) = '0') THEN
            temp_dout := temp_din;
         ELSE
            temp_dout := (OTHERS => 'X');
         END IF;
         temp_din := temp_dout;
      END LOOP;
      dout1 <= temp_dout;
   END PROCESS u_4combo_proc;

   -- Instance port mappings.
   U_0 : gun_position_direction
      PORT MAP (
         btn_value => btn,
         clk       => clk,
         enable    => enable,
         rst       => rst_n,
         x1        => x1,
         y1        => y1
      );

END struct;
