-- VHDL Entity alien_game_lib.gun_position_direction.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 08:06:55 16.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY gun_position_direction IS
   PORT( 
      btn_value : IN     std_logic_vector (3 DOWNTO 0);
      clk       : IN     std_logic;
      enable    : IN     std_logic;
      rst       : IN     std_logic;
      x1        : OUT    std_logic_vector (7 DOWNTO 0);
      y1        : OUT    std_logic_vector (7 DOWNTO 0)
   );

-- Declarations

END gun_position_direction ;

--
-- VHDL Architecture alien_game_lib.gun_position_direction.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 01:30:55 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF gun_position_direction IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout        : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout0       : std_logic;
   SIGNAL dout1       : std_logic_vector(2 DOWNTO 0);
   SIGNAL dout10      : std_logic;
   SIGNAL dout11      : std_logic_vector(1 DOWNTO 0);
   SIGNAL dout12      : std_logic;
   SIGNAL dout13      : std_logic;
   SIGNAL dout14      : std_logic;
   SIGNAL dout2       : std_logic;
   SIGNAL dout3       : std_logic;
   SIGNAL dout4       : std_logic;
   SIGNAL dout5       : std_logic;
   SIGNAL dout6       : std_logic;
   SIGNAL dout7       : std_logic;
   SIGNAL dout8       : std_logic;
   SIGNAL dout9       : std_logic;
   SIGNAL one_hot_out : std_logic_vector(7 DOWNTO 0);
   SIGNAL q           : std_logic_vector(2 DOWNTO 0);
   SIGNAL y           : std_logic_vector(2 DOWNTO 0);
   SIGNAL y2          : std_logic_vector(2 DOWNTO 0);


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'adff'
   SIGNAL mw_U_5reg_cval : std_logic_vector(2 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_11' of 'split'
   SIGNAL mw_U_11temp_din : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_15' of 'split'
   SIGNAL mw_U_15temp_din : std_logic_vector(3 DOWNTO 0);

   -- Component Declarations
   COMPONENT binary_one_hot
   PORT (
      binary_in   : IN     std_logic_vector (2 DOWNTO 0);
      one_hot_out : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT decerementer
   PORT (
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT incrementer
   PORT (
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : binary_one_hot USE ENTITY alien_game_lib.binary_one_hot;
   FOR ALL : decerementer USE ENTITY alien_game_lib.decerementer;
   FOR ALL : incrementer USE ENTITY alien_game_lib.incrementer;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_5' of 'adff'
   q <= mw_U_5reg_cval;
   u_5seq_proc: PROCESS (clk, rst)
   BEGIN
      IF (rst = '0') THEN
         mw_U_5reg_cval <= "000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_5reg_cval <= dout1;
      END IF;
   END PROCESS u_5seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_7' of 'and'
   dout9 <= dout13 AND dout0;

   -- ModuleWare code(v1.12) for instance 'U_14' of 'and'
   dout10 <= dout12 AND dout14;

   -- ModuleWare code(v1.12) for instance 'U_16' of 'and'
   dout3 <= dout14 AND dout0;

   -- ModuleWare code(v1.12) for instance 'U_17' of 'and'
   dout7 <= dout5 AND dout4;

   -- ModuleWare code(v1.12) for instance 'U_19' of 'and'
   dout8 <= enable AND dout7;

   -- ModuleWare code(v1.12) for instance 'U_4' of 'constval'
   y1 <= "10000000";

   -- ModuleWare code(v1.12) for instance 'U_9' of 'inv'
   dout13 <= NOT(dout6);

   -- ModuleWare code(v1.12) for instance 'U_13' of 'inv'
   dout12 <= NOT(dout2);

   -- ModuleWare code(v1.12) for instance 'U_18' of 'inv'
   dout4 <= NOT(dout3);

   -- ModuleWare code(v1.12) for instance 'U_12' of 'merge'
   dout11 <= dout10 & dout9;

   -- ModuleWare code(v1.12) for instance 'U_6' of 'mux'
   u_6combo_proc: PROCESS(q, y, y2, dout11)
   BEGIN
      CASE dout11 IS
      WHEN "00" => dout <= q;
      WHEN "01" => dout <= y;
      WHEN "10" => dout <= y2;
      WHEN "11" => dout <= q;
      WHEN OTHERS => dout <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_6combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'mux'
   u_10combo_proc: PROCESS(q, dout, dout8)
   BEGIN
      CASE dout8 IS
      WHEN '0' => dout1 <= q;
      WHEN '1' => dout1 <= dout;
      WHEN OTHERS => dout1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_10combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_8' of 'or'
   dout5 <= dout0 OR dout14;

   -- ModuleWare code(v1.12) for instance 'U_11' of 'split'
   mw_U_11temp_din <= one_hot_out;
   u_11combo_proc: PROCESS (mw_U_11temp_din)
   VARIABLE temp_din: std_logic_vector(7 DOWNTO 0);
   BEGIN
      temp_din := mw_U_11temp_din(7 DOWNTO 0);
      dout2 <= temp_din(1);
      dout6 <= temp_din(6);
   END PROCESS u_11combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_15' of 'split'
   mw_U_15temp_din <= btn_value;
   u_15combo_proc: PROCESS (mw_U_15temp_din)
   VARIABLE temp_din: std_logic_vector(3 DOWNTO 0);
   BEGIN
      temp_din := mw_U_15temp_din(3 DOWNTO 0);
      dout0 <= temp_din(0);
      dout14 <= temp_din(2);
   END PROCESS u_15combo_proc;

   -- Instance port mappings.
   U_0 : binary_one_hot
      PORT MAP (
         binary_in   => q,
         one_hot_out => one_hot_out
      );
   U_1 : binary_one_hot
      PORT MAP (
         binary_in   => q,
         one_hot_out => x1
      );
   U_3 : decerementer
      PORT MAP (
         x => q,
         y => y2
      );
   U_2 : incrementer
      PORT MAP (
         x => q,
         y => y
      );

END struct;
