-- VHDL Entity alien_game_lib.hit_detector.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 04:55:06 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY hit_detector IS
   PORT( 
      alien_x_cord : IN     std_logic_vector (7 DOWNTO 0);
      clk          : IN     std_logic;
      d            : IN     std_logic;
      gun_x_cord   : IN     std_logic_vector (7 DOWNTO 0);
      rst_n        : IN     std_logic;
      hit          : OUT    std_logic
   );

-- Declarations

END hit_detector ;

--
-- VHDL Architecture alien_game_lib.hit_detector.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 04:55:05 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF hit_detector IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL dout  : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout1 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout2 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout3 : std_logic_vector(7 DOWNTO 0);
   SIGNAL dout4 : std_logic;
   SIGNAL q     : std_logic;
   SIGNAL q1    : std_logic_vector(7 DOWNTO 0);
   SIGNAL q2    : std_logic;
   SIGNAL sel   : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic_vector(7 DOWNTO 0);

   -- ModuleWare signal declarations(v1.12) for instance 'U_1' of 'adff'
   SIGNAL mw_U_1reg_cval : std_logic;

   -- ModuleWare signal declarations(v1.12) for instance 'U_2' of 'adff'
   SIGNAL mw_U_2reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q1 <= mw_U_0reg_cval;
   u_0seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_0reg_cval <= "00000000";
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_0reg_cval <= alien_x_cord;
      END IF;
   END PROCESS u_0seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_1' of 'adff'
   q <= mw_U_1reg_cval;
   u_1seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_1reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_1reg_cval <= d;
      END IF;
   END PROCESS u_1seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_2' of 'adff'
   q2 <= mw_U_2reg_cval;
   u_2seq_proc: PROCESS (clk, rst_n)
   BEGIN
      IF (rst_n = '0') THEN
         mw_U_2reg_cval <= '0';
      ELSIF (clk'EVENT AND clk='1') THEN
         mw_U_2reg_cval <= dout4;
      END IF;
   END PROCESS u_2seq_proc;

   -- ModuleWare code(v1.12) for instance 'U_3' of 'and'
   hit <= dout4 AND NOT(q2);

   -- ModuleWare code(v1.12) for instance 'U_4' of 'and'
   dout2 <= alien_x_cord AND q1;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'and'
   sel <= d AND NOT(q);

   -- ModuleWare code(v1.12) for instance 'U_6' of 'and'
   dout3 <= dout2 AND dout1;

   -- ModuleWare code(v1.12) for instance 'U_9' of 'constval'
   dout <= "00000000";

   -- ModuleWare code(v1.12) for instance 'U_8' of 'mux'
   u_8combo_proc: PROCESS(dout, gun_x_cord, sel)
   BEGIN
      CASE sel IS
      WHEN '0' => dout1 <= dout;
      WHEN '1' => dout1 <= gun_x_cord;
      WHEN OTHERS => dout1 <= (OTHERS => 'X');
      END CASE;
   END PROCESS u_8combo_proc;

   -- ModuleWare code(v1.12) for instance 'U_10' of 'tor'
   dout4 <= dout3(0) OR dout3(1) OR dout3(2) OR dout3(3) OR dout3(4)
            OR dout3(5) OR dout3(6) OR dout3(7);

   -- Instance port mappings.

END struct;
