-- VHDL Entity alien_game_lib.incrementer.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 18:20:03 15.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY incrementer IS
   PORT( 
      x : IN     std_logic_vector (2 DOWNTO 0);
      y : OUT    std_logic_vector (2 DOWNTO 0)
   );

-- Declarations

END incrementer ;

--
-- VHDL Architecture alien_game_lib.incrementer.struct
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 14:06:26 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

LIBRARY alien_game_lib;

ARCHITECTURE struct OF incrementer IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL carry  : std_logic;
   SIGNAL carry1 : std_logic;
   SIGNAL din0   : std_logic;
   SIGNAL din1   : std_logic;
   SIGNAL din2   : std_logic;
   SIGNAL dout   : std_logic;
   SIGNAL dout0  : std_logic;
   SIGNAL dout1  : std_logic;
   SIGNAL dout2  : std_logic;


   -- ModuleWare signal declarations(v1.12) for instance 'U_5' of 'split'
   SIGNAL mw_U_5temp_din : std_logic_vector(2 DOWNTO 0);

   -- Component Declarations
   COMPONENT c1_t1_half_adder
   PORT (
      sw0   : IN     std_logic ;
      sw1   : IN     std_logic ;
      carry : OUT    std_logic ;
      sum   : OUT    std_logic 
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : c1_t1_half_adder USE ENTITY alien_game_lib.c1_t1_half_adder;
   -- pragma synthesis_on


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_3' of 'constval'
   dout <= '1';

   -- ModuleWare code(v1.12) for instance 'U_4' of 'merge'
   y <= din2 & din1 & din0;

   -- ModuleWare code(v1.12) for instance 'U_5' of 'split'
   mw_U_5temp_din <= x;
   u_5combo_proc: PROCESS (mw_U_5temp_din)
   VARIABLE temp_din: std_logic_vector(2 DOWNTO 0);
   BEGIN
      temp_din := mw_U_5temp_din(2 DOWNTO 0);
      dout0 <= temp_din(0);
      dout1 <= temp_din(1);
      dout2 <= temp_din(2);
   END PROCESS u_5combo_proc;

   -- Instance port mappings.
   U_0 : c1_t1_half_adder
      PORT MAP (
         sw0   => dout,
         sw1   => dout0,
         carry => carry,
         sum   => din0
      );
   U_1 : c1_t1_half_adder
      PORT MAP (
         sw0   => carry,
         sw1   => dout1,
         carry => carry1,
         sum   => din1
      );
   U_2 : c1_t1_half_adder
      PORT MAP (
         sw0   => carry1,
         sw1   => dout2,
         carry => OPEN,
         sum   => din2
      );

END struct;
