-- VHDL Entity alien_game_lib.write_sequencer.symbol
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 01:03:37 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY write_sequencer IS
   PORT( 
      alien_defeated : IN     std_logic;
      clk            : IN     std_logic;
      rst            : IN     std_logic;
      write_ready    : IN     std_logic;
      enable         : OUT    std_logic;
      frame_done     : OUT    std_logic;
      gun_px_idx     : OUT    std_logic_vector (2 DOWNTO 0);
      module_select  : OUT    std_logic_vector (1 DOWNTO 0);
      write          : OUT    std_logic
   );

-- Declarations

END write_sequencer ;

--
-- VHDL Architecture alien_game_lib.write_sequencer.fsm
--
-- Created:
--          by - pqm438.UNKNOWN (HTC219-322-SPC)
--          at - 01:03:37 18.12.2024
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2019.3 (Build 4)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;
 
ARCHITECTURE fsm OF write_sequencer IS

   TYPE STATE_TYPE IS (
      s0,
      Start_alien,
      Start_gun,
      gun_px1,
      gun_px2,
      gun_px3,
      gun_px4,
      Enable_and_frame,
      s7
   );
 
   -- Declare current and next state signals
   SIGNAL current_state : STATE_TYPE;
   SIGNAL next_state : STATE_TYPE;

   -- Declare Wait State internal signals
   SIGNAL csm_timer : std_logic_vector(25 DOWNTO 0);
   SIGNAL csm_next_timer : std_logic_vector(25 DOWNTO 0);
   SIGNAL csm_timeout : std_logic;
   SIGNAL csm_to_s7 : std_logic;

BEGIN

   -----------------------------------------------------------------
   clocked_proc : PROCESS ( 
      clk,
      rst
   )
   -----------------------------------------------------------------
   BEGIN
      IF (rst = '0') THEN
         current_state <= s0;
         csm_timer <= (OTHERS => '0');
      ELSIF (clk'EVENT AND clk = '1') THEN
         current_state <= next_state;
         csm_timer <= csm_next_timer;
      END IF;
   END PROCESS clocked_proc;
 
   -----------------------------------------------------------------
   nextstate_proc : PROCESS ( 
      csm_timeout,
      current_state,
      write_ready
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default assignments to Wait State entry flags
      csm_to_s7 <= '0';
      CASE current_state IS
         WHEN s0 => 
            IF (write_ready <= '1') THEN 
               next_state <= Start_alien;
            ELSE
               next_state <= s0;
            END IF;
         WHEN Start_alien => 
            IF (write_ready <= '1') THEN 
               next_state <= Start_gun;
            ELSE
               next_state <= Start_alien;
            END IF;
         WHEN Start_gun => 
            IF (write_ready <= '1') THEN 
               next_state <= gun_px1;
            ELSE
               next_state <= Start_gun;
            END IF;
         WHEN gun_px1 => 
            IF (write_ready <= '1') THEN 
               next_state <= gun_px2;
            ELSE
               next_state <= gun_px1;
            END IF;
         WHEN gun_px2 => 
            IF (write_ready <= '1') THEN 
               next_state <= gun_px3;
            ELSE
               next_state <= gun_px2;
            END IF;
         WHEN gun_px3 => 
            IF (write_ready <= '1') THEN 
               next_state <= gun_px4;
            ELSE
               next_state <= gun_px3;
            END IF;
         WHEN gun_px4 => 
            IF (write_ready <= '1') THEN 
               next_state <= Enable_and_frame;
            ELSE
               next_state <= gun_px4;
            END IF;
         WHEN Enable_and_frame => 
            next_state <= s7;
            csm_to_s7 <= '1';
         WHEN s7 => 
            IF (csm_timeout = '1') THEN 
               next_state <= s0;
            ELSE
               next_state <= s7;
            END IF;
         WHEN OTHERS =>
            next_state <= s0;
      END CASE;
   END PROCESS nextstate_proc;
 
   -----------------------------------------------------------------
   output_proc : PROCESS ( 
      current_state
   )
   -----------------------------------------------------------------
   BEGIN
      -- Default Assignment
      enable <= '0';
      frame_done <= '0';
      gun_px_idx <= (others => '0');
      module_select <= (others => '0');
      write <= '0';

      -- Combined Actions
      CASE current_state IS
         WHEN Start_alien => 
            module_select <= "00";
            write <= '1';
         WHEN Start_gun => 
            module_select <= "01";
            gun_px_idx <= "000";
            write <= '1';
         WHEN gun_px1 => 
            module_select <= "01";
            gun_px_idx <= "001";
            write <= '1';
         WHEN gun_px2 => 
            module_select <= "01";
            gun_px_idx <= "010";
            write <= '1';
         WHEN gun_px3 => 
            module_select <= "01";
            gun_px_idx <= "011";
            write <= '1';
         WHEN gun_px4 => 
            module_select <= "01";
            gun_px_idx <= "100";
            write <= '1';
         WHEN Enable_and_frame => 
            enable <= '1';
            frame_done <= '1';
         WHEN OTHERS =>
            NULL;
      END CASE;
   END PROCESS output_proc;
 
   -----------------------------------------------------------------
   csm_wait_combo_proc: PROCESS (
      csm_timer,
      csm_to_s7
   )
   -----------------------------------------------------------------
   VARIABLE csm_temp_timeout : std_logic;
   BEGIN
      IF (unsigned(csm_timer) = 0) THEN
         csm_temp_timeout := '1';
      ELSE
         csm_temp_timeout := '0';
      END IF;

      IF (csm_to_s7 = '1') THEN
         csm_next_timer <= "10111110101111000001111111"; -- no cycles(50000000)-1=49999999
      ELSE
         IF (csm_temp_timeout = '1') THEN
            csm_next_timer <= (OTHERS=>'0');
         ELSE
            csm_next_timer <= unsigned(csm_timer) - '1';
         END IF;
      END IF;
      csm_timeout <= csm_temp_timeout;
   END PROCESS csm_wait_combo_proc;

END fsm;
